@local=http://localhost:3000

POST {{local}}/cards
Content-Type: application/json

 { "name":"shop", "phone":"05074584", "address":"ddd", "description":"jchjkwhvwjkdvhjkv", "image":"image" }
###


POST {{local}}/users
Content-Type: application/json

{"name":"453","email":"1111.com","password":"123" }


###
POST  {{local}}/auth
Content-Type: application/json

{"email":"user1@g.com"}

###
GET {{local}}/user
Content-Type: application/json

{"email":"reem.tafbdbbfbefbmir36@gmail.com"}

###
POST  {{local}}/token
Content-Type: application/json

{"email":"testsignin@g.com"}


###
POST  {{local}}/auth
Content-Type: application/json

{"email":"testsignin@g.com"}


###
GET {{local}}/cards/63d96c10ca325d8e905b27af
Content-Type: application/json



###
GET {{local}}/all
Content-Type: application/json

###
PUT {{local}}/cards/63d830811fa978c9919a2441
Content-Type: application/json

{  "name":"aaaa",
"address":"aaaa",
    "phone":"aaaaa",
        "description":"aaaa",
        "image":"aaaaa"}
###

DELETE  {{local}}/cards/63d830811fa978c9919a2441
Content-Type: application/json