@local=http://localhost:3000
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0JpeiI6dHJ1ZSwiX2lkIjoiNjNlNzI0OTAxYWNlNjNmOTZmYTQzMGQ2IiwiaWF0IjoxNjc2MDkyNjM2fQ.4XfQVpMuC7gyNGV9leZcBXVPbKk9UsqwmjEoEMY6FR0
POST {{local}}/users/
Content-Type: application/json

 { "name":"dani","email":"11ea3a@gmail.com","password":"Re'eMt23","isBiz":"true"}


###

GET {{local}}/users/me
x-auth-token:{{token}}
Content-Type: application/json


###

POST  {{local}}/auth/
Content-Type: application/json

{ "email":"11ea3a@gmail.com","password":"Re'eMt23"}

###
POST {{local}}/cards/
x-auth-token:{{token}}
Content-Type: application/json


 { "bizName":"dddssssssse","bizPhone":"0507222222","bizAddress":"djjssssdd" ,"bizDescription":"yesssssssss"  }
###
GET {{local}}/cards/my_cards
x-auth-token:{{token}}
Content-Type: application/json


###
GET {{local}}/cards/63e724ff1ace63f96fa430e2
x-auth-token:{{token}}
Content-Type: application/json



###
PUT {{local}}/cards/63e727a33e81201155507762
x-auth-token:{{token}}
Content-Type: application/json

{  "bizName":"hello",
"bizAddress":"aaajjjjja",
    "bizPhone":"023433333",
        "bizDescription":"aaaajjjjjj",
        "bizImage":""}

###

DELETE  {{local}}/cards/63e726f49918b196531fc0ba
x-auth-token:{{token}}
Content-Type: application/json




