@local=http://localhost:3000
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0JpeiI6ZmFsc2UsIl9pZCI6IjYzZTgyYjQ5M2Q3OThmNWU0ZmM3ZDRiMyIsImlhdCI6MTY3NjE1OTkyMX0.YpL89VK6emSydPBHCD2j4aPiTeFG4I8uWgxFTI563wA
POST {{local}}/users/
Content-Type: application/json

 { "name":"dani","email":"1ea344a@gmail.com","password":"Re'eMt23"}


###

GET {{local}}/users/me
x-auth-token:{{token}}
Content-Type: application/json


###

POST  {{local}}/auth/
Content-Type: application/json

{ "email":"1ea344a@gmail.com","password":"Re'eMt23"}

###
POST {{local}}/cards/
x-auth-token:{{token}}
Content-Type: application/json


 { "bizName":"dddssssssse","bizPhone":"0507222222","bizAddress":"djjssssdd" ,"bizDescription":"yesssssssss"  }
###
GET {{local}}/cards/my_cards
x-auth-token:{{token}}
Content-Type: application/json


###
GET {{local}}/cards/63e734a1b75d3ac57f197271
x-auth-token:{{token}}
Content-Type: application/json



###
PUT {{local}}/cards/63e734a1b75d3ac57f197271
x-auth-token:{{token}}
Content-Type: application/json

{  "bizName":"hello",
"bizAddress":"aaajjjjja",
    "bizPhone":"023433333",
        "bizDescription":"aaaajjjjjj",
        "bizImage":""}

###

DELETE  {{local}}/cards/63e734a1b75d3ac57f197271
x-auth-token:{{token}}
Content-Type: application/json




